image: gitpod/workspace-full

ports:
  - port: 5002
    onOpen: open-preview

tasks:
  - init: >
      cp .env.example .env && 
      pipenv install --dev
    command: >
      pipenv run start

  - command: python3 assets/gitpod.py
    openMode: split-right
