pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success=Test / App
      - status-success=Test / Dockerfile
      - base=master
    actions:
      merge:
        method: squash
        strict: true
