name: Docker

on:
  push:
    paths:
      - '.github/workflows/**'
      - '**.py'
      - Pipfile
      - Pipfile.lock
      - .dockerignore
      - Dockerfile

jobs:
  GitHub:
    name: GitHub Package Registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set env vars
        run: |
          echo "::set-env name=USER::$( dirname $GITHUB_REPOSITORY | awk '{print tolower($0)}' )"
          echo "::set-env name=REPO::$( basename $GITHUB_REPOSITORY | awk '{print tolower($0)}' )"
          echo "::set-env name=URL::https://github.com/$( dirname $GITHUB_REPOSITORY | awk '{print tolower($0)}' )/$( basename $GITHUB_REPOSITORY | awk '{print tolower($0)}' )"

      - name: Build
        run: |
          docker build . -t greeter-service:latest \
            --build-arg BUILD_DATE=$(date -u +"%Y-%m-%d") \
            --build-arg VCS_REF=$GITHUB_SHA \
            --build-arg VERSION=$GITHUB_SHA \
            --build-arg VENDOR=$USER \
            --build-arg AUTHOR=$USER \
            --build-arg GIT_REPO=$URL \
            --build-arg DOCUMENTATION=$URL

      - name: Login to GitHub Package Repository
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker login docker.pkg.github.com --username $USER --password $GH_TOKEN

      - name: Tag and push SHA
        run: |
          docker tag greeter-service:latest docker.pkg.github.com/$USER/$REPO/greeter-service:commit-$GITHUB_SHA
          docker push docker.pkg.github.com/$USER/$REPO/greeter-service:commit-$GITHUB_SHA

      - name: Tag and push latest
        if: github.ref == 'refs/heads/master'
        run: |
          docker tag greeter-service:latest docker.pkg.github.com/$USER/$REPO/greeter-service:latest
          docker push docker.pkg.github.com/$USER/$REPO/greeter-service:latest
